### PR TITLE
Strings to bytes

### PR DESCRIPTION
**Pull request by beejeebus**

### CODE REVIEW

**Comment by cpliakas** [comment]
@beejeebus Sorry for the delayed response, was offline for the weekend. Thanks for posting the enhancements, I'm trying them out and wrapping my head around them but I am sure they are an improvement over the current state. This is why we open source things :-) Thanks again for poking around with the tool.

**Comment by cpliakas** [comment]
For some reason it looks like the CPU works a lot harder when I build and run from the pull request compared to what is in master. Memory consumption looks a little higher as well. This isn't a failsafe measure (done via top) however the first image shows the CPU / MEM usage for the app that is built from the pull request, the second is the CPU / MEM usage for the app that is build from master.

screen shot 2016-05-23 at 2 37 24 pm

screen shot 2016-05-23 at 2 39 21 pm

Any idea why this might be?

**Comment by beejeebus** [comment]
hi @cpliakas :-)

yeah, i think the os.OpenFile() change i made was bogus.

looks like named pipes get open and close events a lot, so removing the blocking call made us spin in the scannning code. pushed a new commit without that.

surprise surprise putting two changes together is a bad idea....

**Comment by cpliakas** [comment]
Love the change. `bytes.Equal` is what I was missing and why I went with strings to reduce the byte to string conversions. This is much better. Thanks for the contribution!

**Comment by cpliakas** [comment]
Reflected in the 0.6.0 release.

**Pull request merged**
